land_registry/src/contracts/LandHolder.cairo
land_registry/src/contracts/LandInspector.cairo
land_registry/src/contracts/LandNFT.cairo
land_registry/src/contracts/LandRegistry.cairo
land_registry/src/contracts/LandTransaction.cairo
land_registry/src/contracts/LandVerification.cairo
land_registry/src/models/model_nft.cairo
land_registry/src/models/model_registry.cairo
land_registry/src/models/model_transaction.cairo
land_registry/src/models/model_verification.cairo
land_registry/src/traits/ILandHolder.cairo
land_registry/src/traits/ILandInspector.cairo
land_registry/src/traits/ILandNFT.cairo
land_registry/src/traits/ILandRegistry.cairo
land_registry/src/traits/ILandTransaction.cairo
land_registry/src/traits/ILandVerification.cairo

feat: land registry contracts

---

.github/workflows/build.yml

scarb check workflow on main

---

land_registry/src/interface.cairo
land_registry/src/land_register.cairo
land_registry/src/lib.cairo

- Implemented [feature/new-module]
- Fixed issue with [bug/issue-name]
- Updated documentation for [feature/update-docs]
---
Closes #43 
---
---
---
---
---

feat: update land 

---

.github/PULL_REQUEST_TEMPLATE.md

- Implemented [feature/new-module]
- Fixed issue with [bug/issue-name]
- Updated documentation for [feature/update-docs]
---
Closes #54 
---
---
---
---
---
trimmed pr template

fix: pull request template trimmed

---

frontend/next.config.mjs
frontend/src/app/components/WhyChooseLandver.tsx
frontend/tsconfig.json

fix:linting error

---

frontend/next.config.mjs

fix:removed custom build

---

frontend/src/app/about/page.tsx
frontend/src/app/components/NavBar.tsx
frontend/src/app/components/WhyChooseLandver.tsx

fix: hopeful fix to white header problem

---

frontend/src/app/about/page.tsx
frontend/src/app/components/NavBar.tsx

fix:how it works and background

---

land_registry/src/land_nft.cairo

feat: add landd nft contract

---

.gitignore
land_registry/Scarb.lock
land_registry/Scarb.toml
land_registry/src/land_nft.cairo

- bump OpenZeppelin version
---
---

fix registry

---

.github/workflows/build.yml
land_registry/Scarb.lock
land_registry/Scarb.toml
land_registry/src/lib.cairo
land_registry/src/tests/test_land_register.cairo

- add snforge v0.31.0
- add snforge test workflow
---
---

Add snforge dependency and workflow

---

land_registry/Scarb.toml
land_registry/src/interface.cairo
land_registry/src/land_register.cairo
land_registry/tests/test_land_register.cairo

This PR implements and adds tests for `get_land_count` and `get_lands_by_owner`.
---
Closes #86 
---
---

implement and test get_land_count and get_lands_by_owner

---

land_registry/src/interface.cairo
land_registry/src/land_nft.cairo
land_registry/src/land_register.cairo
land_registry/tests/test_land_register.cairo

Implemented the LandStatus enum, updated the interface, the functions as mentioned, added new functions and tests to test the changes
---
Closes #82 
---
---
- [] All new and existing tests pass.

Implemented and tested LandStatus and Updated Related Functions

---

land_registry/src/interface.cairo
land_registry/src/land_register.cairo
land_registry/tests/test_land_register.cairo

Implement and test the is_land_approved, get_pending_approvals and get_land_transaction_history functions
---
Closes #87 
---
---

Implement and test the is_land_approved, get_pending_approvals and get_land_transaction_history 

---

land_registry/src/land_register.cairo
land_registry/tests/test_land_register.cairo

write test land_transfer
---
Closes #100 
---
---

test: Test transfer land and approve land

---

Landver Design.md

Create Landver Design.md

---

docs/suggestions.md

link to hackmd file for potential updates and improvements

Feature Suggestions for Enhanced Functionality (smart contracts)

---

docs/suggestions.md

 review and suggestions for enhanced functionality

---

docs/suggestions.md

docs:review and suggestions for enhanced functionality on smart contract

---

land_registry/src/interface.cairo
land_registry/src/land_nft.cairo
land_registry/src/land_register.cairo

chore: fix errors and optimise code

---

land_registry/src/custom_error.cairo
land_registry/src/interface.cairo
land_registry/src/land_register.cairo

feat: land market place

---

land_registry/tests/test_land_register.cairo

This pull request introduces a test for the `update_listing_price` function in the contract. The test ensures that the listing price is updated correctly when a valid `listing_id` and `new_price` are provided. It also verifies that unauthorized access is restricted.
---
Closes #153
---
---
---
- **Function Tested:** `update_listing_price`
- **Assertions Added:**
- The `listing_price` is updated correctly in the contract state.
- Validations ensure that unauthorized users cannot call `update_listing_price`.
The test simulates:
1. A valid user updating the price of an existing listing.
2. An invalid user attempting to update the listing price (and failing).
3. Asserting that the price change reflects correctly in the contract's state when authorized.

test for updated listing price

---

landing_page/src/app/components/Footer.tsx
landing_page/src/app/components/NewsLetterCTA.tsx
landing_page/src/app/page.tsx

chore: updated links on footer

---

land_registry/src/interface/land_register.cairo
land_registry/src/land_register.cairo
land_registry/tests/test_integration_land_registry_and_land_nft.cairo
land_registry/tests/test_land_register.cairo

pre-deploy updates

---

land_registry/src/interface/land_register.cairo
land_registry/src/land_register.cairo

Created a function to get all registered lands.
---
Closes #177
---
---

feat: get all lands

---

land_registry/tests/test_land_register.cairo

test: resolve conflicts for test land market functions #151

---

land_registry/src/custom_error.cairo
land_registry/src/interface/land_register.cairo
land_registry/src/land_register.cairo
land_registry/tests/test_integration_land_registry_and_land_nft.cairo
land_registry/tests/test_land_register.cairo

Removed every registration fee implementation(functions,storages,error etc) 
Closes #178
---
- [ x ] 🐛 Bug fix or ⚙️ enhancement
---
- [ x ] The code follows the style guidelines of this project.
- [ x ] All new and existing tests pass.
- [ x ] This pull request is ready to be merged and reviewed.

update: remove fee on register land

---

land_registry/src/interface/land_register.cairo
land_registry/src/land_register.cairo
land_registry/tests/test_land_register.cairo

feat: add function to retrieve inspectors

---

land_registry/src/interface/land_register.cairo
land_registry/src/land_register.cairo
land_registry/tests/test_integration_land_registry_and_land_nft.cairo
land_registry/tests/test_land_register.cairo

remove fees and update interface - test

---

land_registry/src/land_register.cairo
land_registry/tests/test_land_register.cairo

- add test for buy land 
---
Closes #157

test: add test to buy_land function

---

app/client/src/app/layout.tsx

fix:color issue

---

landing_page/src/app/components/RegisterCTA.tsx

feat:implemented get started button

---

landing_page/src/app/components/RegisterCTA.tsx

fix: build issues

---

landing_page/src/app/components/RegisterCTA.tsx

fix: button size

---

land_registry/src/land_register.cairo
land_registry/tests/test_land_register.cairo

fix missing messages when land does not exist
Closes #170 
---
---

fix: return expected error message

---

land_registry/src/land_register.cairo
land_registry/tests/test_land_register.cairo

Reverts NoshonNetworks/landver#204

Revert "fix: return expected error message"

---

.github/workflows/build.yml
land_registry/Scarb.lock
land_registry/Scarb.toml
land_registry/snfoundry.toml

bump worflow versions

---

Landver Design.md

Update Landver Design.md

---

app/server/routes/landRoutes.js
app/server/src/controllers/landController.js
app/server/src/services/blockchainService.js

The setup has been created.
Closes #183

feat: Setup a backend routes for Land event

---

landing_page/package-lock.json
landing_page/package.json
landing_page/src/app/components/Button/Button.tsx
landing_page/src/app/lib/axios.ts
landing_page/src/app/signin/page.tsx
landing_page/src/app/signup/page.tsx

feat:impl auth

---

landing_page/src/app/signup/page.tsx

fix: build

---

landing_page/src/app/signin/page.tsx

fix:endpoint issues

---

landing_page/src/app/signin/page.tsx

fix:password to passcode

---

landing_page/src/app/signup/page.tsx

fix : phrasing

---

landing_page/src/app/signup/page.tsx

fix:rename

---

app/client/src/components/Connector.tsx
app/client/src/components/Modal/Modal.tsx
app/client/src/components/WalletConnectModal.tsx

fix: modal content and error messages

---

app/client/src/app/page.tsx
app/client/src/components/Connector.tsx
app/client/src/components/Modal/Modal.tsx

fix: updated modal design

---

README.md

fix: monorepo setup

---

app/client/src/app/page.tsx
app/client/src/components/Connector.tsx
app/client/src/components/Navbar.tsx

Added all necessary spinners as directed in issue
Closes #250 
---
---

refac: add all necessary loading states

---

app/client/src/app/Providers.tsx
app/client/src/components/WalletConnectModal.tsx

Removed all traces of the argent wallet connector
---
Closes #245 
---
---

feat: remove argent web wallet connector

---

app/client/src/app/(main)/(wallet-connection-needed)/Providers.tsx
app/client/src/app/(main)/(wallet-connection-not-needed)/Providers.tsx
app/client/src/components/WalletConnectModal.tsx

Store in LS the used wallet when login to fix that somethimes reconnection on refresh do not work

fix connector error when setting on LS

---

docs/land_nft.md
docs/land_registry.md
land_registry/src/interface/land_nft.cairo
land_registry/src/interface/land_register.cairo
land_registry/src/land_nft.cairo
land_registry/src/land_register.cairo
land_registry/src/utils.cairo
land_registry/tests/test_integration_land_registry_and_land_nft.cairo
land_registry/tests/test_land_nft.cairo
land_registry/tests/test_land_register.cairo

feat: update entire contract

---

landing_page/package.json
landing_page/src/app/components/Benefits.tsx
landing_page/src/app/components/Footer.tsx
landing_page/src/app/components/Hero.tsx
landing_page/src/app/components/NavBar.tsx
landing_page/src/app/components/NewsLetterCTA.tsx
landing_page/src/app/components/RegisterCTA.tsx
landing_page/src/app/components/WhyChooseLandver.tsx
landing_page/src/app/utils/animations.js
landing_page/tsconfig.json

---
Closes #301 
---
- [] 🐛 Bug fix or ⚙️ enhancement
---
- [] All new and existing tests pass.

feat: add animations to enhance landing page #301

---

app/client/src/app/layout.tsx
app/client/src/components/WalletConnectModal.tsx

fix:scrolling
